### ISSUE TITLE
Timeline for beta?

### ISSUE THREAD

**Issue by xeoncross** [targodan/goad#1]
Your development branch looks good (though I haven't run it). Any timeline for pushing to master?

**Comment by targodan** [comment]
Glad you like it.

To be honest I kind of forgot about this project. 😅 
Sure, I guess I could make a 0.1 release. I will try and make time to hammer together the release in the next couple of days.

**Comment by targodan** [comment]
Just hammered together a small release. Hope it helps you. 😉

**Comment by xeoncross** [comment]
Thanks a lot! I've worked on other audio sampling libs but your [getSample](https://github.com/targodan/goad/blob/master/decoder.go#L187) is well done handling even doubles and other uncommon audio sample rates.
